name: Databricks-CI-CD
on:
  workflow_dispatch:
    inputs:
      GIT_NOTEBOOK_PATH:
        description: 'Notebooks Relative Path in Git'
        required: true
        default: 'notebooks/fin_data'

      NOTEBOOK_DEPLOYMENT_PATH:
        description: 'Notebooks Deployment Path to Databricks'
        required: true
        default: '/fin_data'

      RESOURCE_GROUP:
        description: 'Resource Group Name'
        required: true
        default: 'pet_projects'

      WORKSPACE_NAME:
        description: 'Databricks workspace name'
        required: true
        default: 'dataprocessing'


jobs:
#############################################################
# Builds the code
# This is packaging up the files from Git to the Artifacts files
#############################################################
  Build:
    runs-on: ubuntu-latest
    steps:
    # Display the event that triggered the workflow
    - run: echo "The job was triggered by a ${{ github.event_name }} event."
      
    # Runner information
    - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub"
      
    # Information about the repository and branch
    - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2    

    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

    - run: echo "Your repository has been copied to the path ${{ github.workspace }} on the runner."

    # Publish Artifact: Databricks-Notebooks
    - name: 'Publish Artifact: Databricks-Notebooks' 
      uses: actions/upload-artifact@v2
      with:
        name: 'notebooks'
        path: '${{ github.workspace }}/notebooks'

    # Publish Artifact: Databricks-Deployment-Scripts
    - name: 'Publish Artifact: Databricks-Deployment-Scripts' 
      uses: actions/upload-artifact@v2
      with:
        name: 'deployment-scripts'
        path: '${{ github.workspace }}/deployment-scripts'  

#############################################################
# Deploy
#############################################################
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    # Download Artifact: Databricks-Notebooks
    - name: 'Download Artifact: Databricks-Notebooks' 
      uses: actions/download-artifact@v2
      with:
        name: 'notebooks'
        path: ${{ github.workspace }}/notebooks

    # Download Artifact: Deployment Scripts
    - name: 'Download Artifact: Deployment Scripts' 
      uses: actions/download-artifact@v2
      with:
        name: 'deployment-scripts'
        path: ${{ github.workspace }}/deployment-scripts

    # Deploy Databricks Notebooks
    - name: Deploy Databricks Notebooks
      run: |
        cd "$GITHUB_WORKSPACE/${{ github.event.inputs.GIT_NOTEBOOK_PATH }}"
        chmod +x $GITHUB_WORKSPACE/deployment-scripts/deploy-notebooks.sh
        $GITHUB_WORKSPACE/deployment-scripts/deploy-notebooks.sh ${{ secrets.AZURE_TENANT_ID }} ${{ secrets.AZURE_CLIENT_ID }} ${{ secrets.AZURE_CLIENT_SECRET }} ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ github.event.inputs.RESOURCE_GROUP }} ${{ github.event.inputs.WORKSPACE_NAME }} ${{ github.event.inputs.NOTEBOOK_DEPLOYMENT_PATH }}
